// The host-artifact contract between install.sh and updater/apply.sh.
//
// Everything the companion puts on the server outside its containers is a "host
// artifact": the runtime files in the install directory, the one command on
// PATH, and the symlink pointing at it. install.sh writes them on a fresh box;
// apply.sh has to keep them current on every upgrade. When those two lists
// disagree, the difference silently rots — a box installed before a file existed
// never gets it, and a changed file never reaches an existing box.
//
// That already happened: `shockwave-fingerprint` and `shockwave-rotate-cert`
// were generated by install.sh and existed nowhere else, so no upgrade could
// ever deliver them. Boxes installed before they landed simply had no such
// command, and there was no way to find that out except typing it.
//
// These tests pin the rules that make the drift impossible rather than merely
// currently-absent:
//
//   1. Every runtime file install.sh fetches is also fetched by apply.sh
//      (except init.sql — see below), so adding one teaches upgrades about it.
//   2. install.sh creates exactly ONE symlink on PATH, to the dispatcher.
//   3. apply.sh creates NO symlinks. It cannot: watch.sh mounts only the install
//      directory into the helper that runs it. This is what makes rule 2 load-
//      bearing — the symlink target must never change, or upgrades can't
//      maintain it.
//   4. Files that get executed directly are chmod'd by both.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const install = fs.readFileSync(path.join(root, 'api/install.sh'), 'utf8');
const apply = fs.readFileSync(path.join(root, 'api/updater/apply.sh'), 'utf8');

// The command on PATH. One file, one symlink, forever.
const DISPATCHER = 'host/shockwave';

// init.sql is deliberately install-only: the api image carries its own copy and
// re-applies it at every boot (ensureSchema), so a stale one on the host is
// inert. Every other runtime file is live and must track the release.
const INSTALL_ONLY = new Set(['init.sql']);

function installFetchList() {
  const m = /^for f in (.+?); do$/m.exec(install);
  assert.ok(m, 'could not find install.sh\'s runtime-file fetch loop');
  return m[1].trim().split(/\s+/);
}

function applyFileList() {
  const m = /^FILES="([^"]+)"$/m.exec(apply);
  assert.ok(m, 'could not find apply.sh\'s FILES list');
  return m[1].trim().split(/\s+/);
}

test('every runtime file install.sh fetches is also refreshed by upgrades', () => {
  const upgraded = new Set(applyFileList());
  const missing = installFetchList().filter((f) => !INSTALL_ONLY.has(f) && !upgraded.has(f));
  assert.deepEqual(missing, [],
    `install.sh writes these to the host but apply.sh never refreshes them, so they rot: ${missing.join(', ')}. `
    + 'Add them to FILES in api/updater/apply.sh, or to INSTALL_ONLY here with a reason.');
});

test('the dispatcher is delivered by both paths', () => {
  assert.ok(installFetchList().includes(DISPATCHER), 'install.sh must fetch ' + DISPATCHER);
  assert.ok(applyFileList().includes(DISPATCHER), 'apply.sh must refresh ' + DISPATCHER);
});

test('install.sh creates exactly one symlink on PATH, to the dispatcher', () => {
  const links = [...install.matchAll(/ln -sf?\s+"?([^"\s]+)"?\s+"?(\/usr\/local\/bin\/[^"\s]+)"?/g)]
    .map((m) => ({ target: m[1], link: m[2] }));
  assert.equal(links.length, 1,
    `expected exactly 1 symlink into /usr/local/bin, found ${links.length}: ${links.map((l) => l.link).join(', ')}. `
    + 'Add subcommands to api/host/shockwave instead — a new symlink is a host artifact upgrades cannot create.');
  assert.match(links[0].target, /\$DIR\/host\/shockwave$/);
  assert.equal(links[0].link, '/usr/local/bin/shockwave');
});

// Comments explain these rules, so matching raw text would flag the explanation
// as a violation. Assert against the code only.
const code = (sh) => sh.split('\n').filter((l) => !/^\s*#/.test(l)).join('\n');

test('apply.sh creates no symlinks and writes nothing outside the install dir', () => {
  assert.doesNotMatch(code(apply), /\bln -s/,
    'apply.sh cannot make symlinks — watch.sh mounts only $COMPANION_DIR into its helper.');
  assert.doesNotMatch(code(apply), /\/usr\/local\/bin/,
    'apply.sh cannot write to /usr/local/bin — it is not mounted.');
});

test('directly-executed host files are made executable by both paths', () => {
  const m = /^EXECUTABLE="([^"]+)"$/m.exec(apply);
  assert.ok(m, 'apply.sh must declare EXECUTABLE (curl writes 644; mv preserves it)');
  const execFiles = m[1].trim().split(/\s+/);
  assert.ok(execFiles.includes(DISPATCHER), 'the dispatcher runs via a symlink, so its mode matters');
  for (const f of execFiles) {
    assert.match(install, new RegExp(`chmod 755 "\\$DIR/${f.replace('/', '\\/')}"`),
      `install.sh must also chmod 755 ${f}`);
    // And it ships executable, so a git checkout / dev run behaves the same.
    const st = fs.statSync(path.join(root, 'api', f));
    assert.ok(st.mode & 0o111, `api/${f} must be executable in the repo`);
  }
});
